In [4]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [53]:
results = pd.read_csv('../results/results_summary_test.csv')

In [54]:
results[(results['track'] == 'closed') & (results['model'].str.contains('Mean_mha'))].sort_values('rmse')

,track,split,model,L1,rmse,pearson
24,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_cn_new,cn,0.962969,0.823815
25,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_de_new,de,1.123044,0.781365
26,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_es_new,es,1.403854,0.674560

In [21]:
results[results['model'].str.contains('mtl')].sort_values('rmse')

,track,split,model,L1,rmse,pearson
58,open,test,mbert-base_mtl_mlp_Mean_cls_last4_open_xx,cn,0.891697,0.848132
52,open,test,mbert-base_mtl_mlp_Max_mean_open_xx,cn,0.893123,0.847187
49,open,test,mbert-base_mtl_mlp_Max_mean_last4_open_xx,cn,0.902316,0.843697
73,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,cn,0.904612,0.843304
55,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,cn,0.917619,0.839972
67,open,test,mbert-base_mtl_mlp_cls_open_xx_new,cn,0.926646,0.836011
61,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,cn,0.938465,0.833240
70,open,test,mbert-base_mtl_mlp_mean_open_xx_new,cn,0.943336,0.830587
27,closed,test,mbert-base_mtl_mlp_mean_closed_cn_new,cn,0.957369,0.821875
57,open,test,mbert-base_mtl_mlp_Mean_cls_last4_open_xx,de,0.984022,0.836340
48,open,test,mbert-base_mtl_mlp_Max_mean_last4_open_xx,de,0.991581,0.833777
24,closed,test,mbert-base_mtl_mlp_cls_closed_cn_new,cn,0.994846,0.806527
51,open,test,mbert-base_mtl_mlp_Max_mean_open_xx,de,0.995171,0.832318
8,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_de,de,1.021157,0.822505
72,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,de,1.027016,0.821957
66,open,test,mbert-base_mtl_mlp_cls_open_xx_new,de,1.032187,0.819864
69,open,test,mbert-base_mtl_mlp_mean_open_xx_new,de,1.045438,0.817155
10,closed,test,mbert-base_mtl_mlp_Max_mha_last4_1_closed_cn_new,cn,1.050694,0.783957
60,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,de,1.053596,0.813490
32,closed,test,mbert-base_mtl_mlp_mha_1_closed_de,de,1.056056,0.810319
54,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,de,1.057356,0.813611
18,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_cn_new,cn,1.060195,0.778719
56,open,test,mbert-base_mtl_mlp_Mean_cls_last4_open_xx,es,1.068224,0.823772
71,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,es,1.072218,0.822631
47,open,test,mbert-base_mtl_mlp_Max_mean_last4_open_xx,es,1.076865,0.820460
50,open,test,mbert-base_mtl_mlp_Max_mean_open_xx,es,1.077005,0.820251
19,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_de_new,de,1.083143,0.799010
25,closed,test,mbert-base_mtl_mlp_cls_closed_de_new,de,1.084500,0.799419
53,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,es,1.090269,0.819609
68,open,test,mbert-base_mtl_mlp_mean_open_xx_new,es,1.095849,0.814560
65,open,test,mbert-base_mtl_mlp_cls_open_xx_new,es,1.097136,0.813985
29,closed,test,mbert-base_mtl_mlp_mean_closed_de_new,de,1.106010,0.789843
6,closed,test,mbert-base_mtl_mlp_Max_mean_closed_es,es,1.106889,0.809077
59,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,es,1.141191,0.802386
34,closed,test,mbert-base_mtl_mlp_mha_1_closed_es_new,es,1.155065,0.793167
20,closed,test,mbert-base_mtl_mlp_Mean_mha_last4_1_closed_es_new,es,1.166230,0.786022
30,closed,test,mbert-base_mtl_mlp_mean_closed_es_new,es,1.168590,0.786177
12,closed,test,mbert-base_mtl_mlp_Max_mha_last4_1_closed_es_new,es,1.181409,0.781341
31,closed,test,mbert-base_mtl_mlp_mha_1_closed_cn_new,cn,1.249395,0.669010
16,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_cn,cn,1.288703,0.645754
64,open,test,mbert-base_mtl_mlp_cls_open_xx,cn,1.307353,0.633344
7,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_cn,cn,1.311327,0.634096
13,closed,test,mbert-base_mtl_mlp_Mean_cls_last4_closed_cn,cn,1.326085,0.620486
23,closed,test,mbert-base_mtl_mlp_cls_closed_cn,cn,1.342992,0.614482
33,closed,test,mbert-base_mtl_mlp_mha_1_closed_de_new,de,1.372391,0.645453
28,closed,test,mbert-base_mtl_mlp_mean_closed_de,de,1.378679,0.643518
63,open,test,mbert-base_mtl_mlp_cls_open_xx,de,1.402967,0.628092
14,closed,test,mbert-base_mtl_mlp_Mean_cls_last4_closed_de,de,1.435479,0.607788
11,closed,test,mbert-base_mtl_mlp_Max_mha_last4_1_closed_de_new,de,1.439602,0.600305
9,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_es,es,1.466211,0.630212
62,open,test,mbert-base_mtl_mlp_cls_open_xx,es,1.524023,0.601773
17,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_es,es,1.558475,0.564960
26,closed,test,mbert-base_mtl_mlp_cls_closed_es_new,es,1.607117,0.528307
15,closed,test,mbert-base_mtl_mlp_Mean_cls_last4_closed_es,es,1.609870,0.524442
21,closed,test,mbert-base_mtl_mlp_ScalarMix_mha_last4_1_close...,de,1.673887,0.407820
22,closed,test,mbert-base_mtl_mlp_ScalarMix_mha_last4_1_close...,es,1.851516,0.226952

In [7]:
results[~results['model'].str.contains('mtl')].sort_values('rmse')

,track,split,model,L1,rmse,pearson
49,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,cn,0.907935,0.842887
55,open,test,mbert-base_mlp_mha_1_open_xx_new,cn,0.908775,0.841263
52,open,test,mbert-base_mlp_cls_open_xx_new,cn,0.960160,0.822198
3,closed,test,mbert-base_mlp_cls_closed_cn_new,cn,1.005903,0.802733
54,open,test,mbert-base_mlp_mha_1_open_xx_new,de,1.030439,0.820059
48,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,de,1.032346,0.819475
51,open,test,mbert-base_mlp_cls_open_xx_new,de,1.046879,0.815395
47,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,es,1.083480,0.818402
53,open,test,mbert-base_mlp_mha_1_open_xx_new,es,1.084171,0.819952
46,open,test,baseline_open_xx,cn,1.092162,0.802026
4,closed,test,mbert-base_mlp_cls_closed_de_new,de,1.097959,0.792499
50,open,test,mbert-base_mlp_cls_open_xx_new,es,1.118242,0.809102
45,open,test,baseline_open_xx,de,1.203948,0.798242
0,closed,test,baseline_closed_cn,cn,1.213908,0.694751
5,closed,test,mbert-base_mlp_cls_closed_es_new,es,1.229159,0.759321
44,open,test,baseline_open_xx,es,1.259071,0.773603
1,closed,test,baseline_closed_de,de,1.281594,0.714080
2,closed,test,baseline_closed_es,es,1.336755,0.742175

In [9]:
results[(results['model'].str.contains('mha')) & (results['track'] == 'open')].sort_values('rmse')

,track,split,model,L1,rmse,pearson
91,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,cn,0.904612,0.843304
49,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,cn,0.907935,0.842887
55,open,test,mbert-base_mlp_mha_1_open_xx_new,cn,0.908775,0.841263
67,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,cn,0.917619,0.839972
76,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,cn,0.938465,0.833240
90,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,de,1.027016,0.821957
54,open,test,mbert-base_mlp_mha_1_open_xx_new,de,1.030439,0.820059
48,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,de,1.032346,0.819475
75,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,de,1.053596,0.813490
66,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,de,1.057356,0.813611
89,open,test,mbert-base_mtl_mlp_mha_1_open_xx_new,es,1.072218,0.822631
47,open,test,mbert-base_mlp_Max_mha_last4_1_open_xx_new,es,1.083480,0.818402
53,open,test,mbert-base_mlp_mha_1_open_xx_new,es,1.084171,0.819952
65,open,test,mbert-base_mtl_mlp_Max_mha_last4_1_open_xx_new,es,1.090269,0.819609
74,open,test,mbert-base_mtl_mlp_Mean_mha_last4_1_open_xx_new,es,1.141191,0.802386

In [10]:
results[(results['model'].str.contains('mean')) & (results['track'] == 'closed')].sort_values('rmse')

,track,split,model,L1,rmse,pearson
20,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_cn_new,cn,0.952787,0.823839
8,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_cn_new,cn,0.954758,0.823935
36,closed,test,mbert-base_mtl_mlp_mean_closed_cn_new,cn,0.957369,0.821875
9,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_de,de,1.021157,0.822505
10,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_de_new,de,1.068109,0.805932
38,closed,test,mbert-base_mtl_mlp_mean_closed_de_new,de,1.106010,0.789843
6,closed,test,mbert-base_mtl_mlp_Max_mean_closed_es,es,1.106889,0.809077
23,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_es_new,es,1.136813,0.798948
12,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_es_new,es,1.141471,0.796773
39,closed,test,mbert-base_mtl_mlp_mean_closed_es_new,es,1.168590,0.786177
19,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_cn,cn,1.288703,0.645754
7,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_cn,cn,1.311327,0.634096
37,closed,test,mbert-base_mtl_mlp_mean_closed_de,de,1.378679,0.643518
21,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_de_new,de,1.408902,0.628114
11,closed,test,mbert-base_mtl_mlp_Max_mean_last4_closed_es,es,1.466211,0.630212
22,closed,test,mbert-base_mtl_mlp_Mean_mean_last4_closed_es,es,1.558475,0.564960
27,closed,test,mbert-base_mtl_mlp_ScalarMix_mean_last4_closed_cn_new,cn,1.646737,0.210567
28,closed,test,mbert-base_mtl_mlp_ScalarMix_mean_last4_closed_de_new,de,1.748991,0.245288
29,closed,test,mbert-base_mtl_mlp_ScalarMix_mean_last4_closed_es_new,es,1.833727,0.240257